image: node:latest

stages:
#  - release
  - build
  - publish

build:
  stage: build
  only:
    - master
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/
      - package.json
  script:
    - git config user.email peter@ocelotworks.com
    - git config user.name "GitLab"
    - npm install -g typescript
    - npm config set registry $NPM_REGISTRY
    - npx semantic-release
#    - npm version $(cat .next-version) --allow-same-version
    - npm install
    - tsc

publish:
  stage: publish
  only:
    - master
  artifacts:
    paths:
      - dist/
      - package.json
  script:
    - git config user.email peter@ocelotworks.com
    - git config user.name "GitLab"
    - npm config set allow-same-version true
    - npm config set registry $NPM_REGISTRY
    - npm install -g npm-cli-login
    - npm-cli-login -u $NPM_USER -p $NPM_PASSWORD -e $NPM_EMAIL -r $NPM_REGISTRY
    - npm publish
